export interface MetalUnitModel{
    metalUnitId: number,
    id:number,
    metalUnit: string,
    partIndex: string,
    sequenceNumber: number,
    hasValidationErrors: boolean,
    coilPartNumber: string, 
    coilNumber:string,
    partNumber: string,
    batchName: string,
    operation: string,
    macroArticle: string,
    weight: number,
    hotWeight: number,
    steelgrade: string,
    finishing: string,
    shape: string
    nextMetalMovementId: number
    length: number,
    width: number,
    thickness: number,
    no: string,
    type: string,
    packageType: string,
    packageNo: string,
    packageClass: string,
    comment: string, 
    consumedBySameMetalMovement:boolean,
}